
joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint", "arm_7_joint"]
tip_link: 'arm_7_link'
base_link: 'arm_base_link'

tracking_frame: "br"
reference_frame: "world" 
endeffector_frame: "arm_7_link"
axis : "trans.x"
trans_x : 0
trans_y : 0
trans_z : 0
rot_x : 0.1
rot_y : 0.1
rot_z : 0.1
samples : 100
