joint_names: ["torso_1_link","torso_2_link","torso_3_link"]
tip_link: 'torso_3_link'
base_link: 'torso_base_link'
output_file_path: "/home/fxm-cm_local/m-files/"

tracking_frame: "br"
reference_frame: "torso_base_link" 
endeffector_frame: "torso_3_link"

trans_x : 0
trans_y : 0
trans_z : 0
rot_x : 0.05
rot_y : 0.05
rot_z : 0.05
samples : 100
