# goal definition
string name
float64 hold_time

cob_cartesian_controller/MoveLin move_lin
cob_cartesian_controller/MoveCirc move_circ

---
# result definition
bool success
string message
---
# Define a feedback message
