// ROS message includes
#include "ros/ros.h"
#include <std_msgs/String.h>

/* protected region user include files on begin */
/* protected region user include files end */

class cob_test_action_client_config
{
public:
};

class cob_test_action_client_data
{
// autogenerated: don't touch this class
public:
    //input data
    std_msgs::String in_saub;
    //output data
};

class cob_test_action_client_impl
{
    /* protected region user member variables on begin */
    /* protected region user member variables end */

public:
    cob_test_action_client_impl() 
    {
        /* protected region user constructor on begin */
        /* protected region user constructor end */
    }

    void configure(cob_test_action_client_config config) 
    {
        /* protected region user configure on begin */
        /* protected region user configure end */
    }

    void update(cob_test_action_client_data &data, cob_test_action_client_config config)
    {
        /* protected region user update on begin */
    	ROS_INFO("Hey I am running ---");

        /* protected region user update end */
    }


    /* protected region user additional functions on begin */
    /* protected region user additional functions end */
};
