name: GHA CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight
  workflow_dispatch:

jobs:
  industrial_ci:
    name: GHA CI
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ADDITIONAL_DEBS: 'apt-utils dialog git'
      CATKIN_LINT: pedantic
      CATKIN_LINT_ARGS: '--ignore description_boilerplate'
      CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release
      DOCKER_IMAGE: 'ghcr.io/mojin-robotics/mojin-ros:amr-full'  # use DOCKER_IMAGE to speedup install_*_dependencies steps
      PYLINT_ARGS: '--output-format=parseable --errors-only'
      PYLINT_CHECK: true
      ROS_REPO: main
      SECRET_AVAILABLE: ${{secrets.GITHUBPAT}}
      UNDERLAY: '/opt/node'  # use navigation binaries instead of substitutes

    strategy:
      matrix:
        include:
          - { ROS_DISTRO: noetic }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
          ssh-known-hosts: ''

      - uses: docker/login-action@v3
        if: ${{ env.SECRET_AVAILABLE }} # prevents failure notifications if secret GITHUBPAT is not available
        with:
          registry: ghcr.io
          username: mojin-robotics-ci
          password: ${{ secrets.GITHUBPAT }}

      - uses: ros-industrial/industrial_ci@master
        if: ${{ env.SECRET_AVAILABLE }} # prevents failure notifications if secret GITHUBPAT is not available
        with:
          config: ${{toJSON(matrix)}}
